// DATA CALON KOTA DAPIL 1
const PKB = {
	nomer: 1,
	nama: "PKB",
	dapil: "DAPIL 1",
	1: "HANI FIDYANTO",
	2: "AIS SHAFIYAH ASFAR",
	3: "IMAM MUSTAJI, S.E.",
	4: "MOHAMMAD HIDAYATULLAH",
	5: "ZAINAL ABIDIN",
	6: "QOTRUNNADA LAILA MUFIDAH",
	7: "AHMAT FAUZI",
	8: "SAIFUL BAHRI",
	9: "ALICYA INUNG FATMA",
	10: "ACHMAD RIFAI",
};

const GERINDRA = {
	nomer: 2,
	nama: "GERINDRA",
	dapil: "DAPIL 1",
	1: "AJENG WIRA WATI, S.Sos.",
	2: "AZHAR KAHFI, S.H.",
	3: "MARSEKAN IBRAHIM, S.H.",
	4: "SAYULI SUKARDIONO",
	5: "VERONICA ENDANG PRIASTUTI, S.E.",
	6: "ERWAN GUNANDA PUTRA, S.Psi.",
	7: "FAISAL ISNAINI, S.Pd.",
	8: "YOSI IKA MAHARANI, S.E.",
	9: "H. ACHMAD SETYO KARNO",
	10: "Hj. JULI NURANI, S.H., M.H.",
};

const PDIP = {
	nomer: 3,
	nama: "PDIP",
	dapil: "DAPIL 1",
	1: "Drs. R. TARU SASMITA",
	2: "H. TRI DIDIK ADIONO, S.Sos.",
	3: "NORMA YUNITA, S.H.",
	4: "BUDI LEKSONO, S.H.",
	5: "ACHMAD HIDAYAT, S.Sos.",
	6: "AISYAH JATU KUSUMAWATI, S.Sosio.",
	7: "ARIF HIDAYAT",
	8: "TRIWURYANI",
	9: "Drs. EDI SANTOSO, M.Si.",
	10: "FAYAKUNDIA PUTRA S, S.H., M.Kn.",
};

const GOLKAR = {
	nomer: 4,
	nama: "GOLKAR",
	dapil: "DAPIL 1",
	1: "ALDY BLAVIANDY, S.Psi.",
	2: "ERICK REGINALD TAHALELE, S.Sos.",
	3: "Hj. DJAYATI",
	4: "Dra. Ec. Hj. PERTIWI AYU K, M.M.",
	5: "ADI PATMA NUSANTARA, S.E.",
	6: "M. DALLY BARMASSYAH, S.H.",
	7: "Hj. DENNY ERNAWATI",
	8: "FADHEL KURNIAWAN, S.E.",
	9: "CHAKRA SATRYA PRADANA P A, S.Kom.",
	10: "HADI SURYO SISWOYO, S.I.P.",
};

const NASDEM = {
	nomer: 5,
	nama: "NASDEM",
	dapil: "DAPIL 1",
	1: "Drs. H. IMAM SYAFI'I, S.H.",
	2: "ENDANG RINI ASIH",
	3: "TJATUR SETIONO",
	4: "RR. AGUSTIEN LILAWATI.",
	5: "ANITA FARIDA",
	6: "NURKHASANAH YULISTIANI",
	7: "MEI SETYANINGSIH, S.Pd., M.Pd",
	8: "NURUL MUZAYANAH, S.Pi., M.M.",
	9: "ROMNDONI",
	10: "KAROLINA",
};

const PARTAI_BURUH = {
	nomer: 6,
	nama: "PARTAI_BURUH",
	dapil: "DAPIL 1",
	1: "YUZAK DAUD SILOY",
	2: "Ir. ADI HUDA",
	3: "ANDRI RIA PUTRI",
	4: "M. HUZAINI AMIN",
	5: "BYFTHA GERALDO AJAWAILA",
	6: "ARIANA BUSJRONI, S.Psi.",
	7: "ABDUL AZIS",
	8: "HENGKY FIDRIANTA",
	9: "ANIS SUSANTI EKA P., S.E.",
	10: "FIRMAN SIDQI MULANOVANDA",
};

const GELORA = {
	nomer: 7,
	nama: "GELORA",
	dapil: "DAPIL 1",
	1: "dr. ANNA SUSANTI, M.M.",
	2: "DJOKO JUNIWAHONO",
	3: "HERMAN SOEDJADI",
	4: "MUNTAZ HIRA",
	5: "RAHMAN HAKIM",
	6: "ASHIM",
	7: "AGUNG SANTOSA",
	8: "KURNIA DWI SANTI H, S.E.",
	9: "ELINDA MILLENIA ALISIYA",
	10: "IQBAL RAMADHAN ZAMI",
};

const PKS = {
	nomer: 8,
	nama: "PKS",
	dapil: "DAPIL 1",
	1: "Hj. ENNY MINARSIH",
	2: "DYAH WULANDARI, S.P.",
	3: "HIMAS MUHAMMMADY I. EL HAKIM",
	4: "ZAINUDDIN",
	5: "MUZAN THOIB, S.Pd.",
	6: "NANING HARIYATI",
	7: "HAMAS SYAHID IZZUDDIN",
	8: "ARIEF HERCAHYANTO",
	9: "LILIS SURYANI",
	10: "BASUKI ABDUL AZIZ, S.Si.",
};

const PKN = {
	nomer: 9,
	nama: "PKN",
	dapil: "DAPIL 1",
	1: "ERWIN SISWANTO",
	2: "LISANA PUJI ASTUTI, S.Sn.",
};

const HANURA = {
	nomer: 10,
	nama: "HANURA",
	dapil: "DAPIL 1",
	1: "BUDI SETIAWAN, S.E., M.Si.",
	2: "AGUNG SATRYO WIBOWO, S.E., M.M.",
	3: "IDA RACHMAYANTI, A.Md.",
	4: "Ir. ARIEF SOSIAWAN",
	5: "MOHAMAD WAWAN FAUZI, S.T.",
	6: "ARIE SENJA RAHMAWATI",
	7: "ACHMAD GOESSJAHEINNIE R, S.H.",
	8: "OEDIN HERMANTO",
	9: "IDA PURWATI",
	10: "SYAMSUL ARIFIN",
};

const PARTAI_GARUDA = {
	nomer: 11,
	nama: "PARTAI_GARUDA",
	dapil: "DAPIL 1",
	1: "ROSSA PANGANDAHENG, S.H.",
	2: "NICOLAS SINGAL",
	3: "NUR INSANA",
	4: "LUCAS ABDUL ARDIANSYAH, S.H.",
	5: "ENDANG PUDJIANI SETIOWATI, S.E.",
};

const PAN = {
	nomer: 12,
	nama: "PAN",
	dapil: "DAPIL 1",
	1: "dr. Hj. ZUHROTUL MAR'AH",
	2: "KUSPRIYANTO",
	3: "H. SLAMET EFFENDI",
	4: "DINDA HIKMATULLAH FERDYAN",
	5: "BUDI SUSANTO, A.M.Tr.D.",
	6: "NOERYADI",
	7: "NURANA MUSHOWAROH",
	8: "SUTRISNO",
	9: "H.R. MOCH DJUPRI SA'AD ABU S",
	10: "AKBAR BRILLIANTO",
};

const PBB = {
	nomer: 13,
	nama: "PBB",
	dapil: "DAPIL 1",
	1: "SYAIFUL ARIFIN",
	2: "SOLECHAH, S.E.",
	3: "RIVAN ELNANDO PRASUCI SETYAWAN",
	4: "BAGUS RIZKI WICAKSONO, S.H.",
	5: "SITI FADILLAH",
	6: "RIEKO AGUSTINO, S.Kom.",
	7: "AGUS BUDIONO AFFANDI",
	8: "DEDY ZULKARNAEN",
	9: "YULIATI",
};

const DEMOKRAT = {
	nomer: 14,
	nama: "DEMOKRAT",
	dapil: "DAPIL 1",
	1: "H. JUNAEDI, S.E.",
	2: "Drs. SACHIROEL ALIM ANWAR",
	3: "SEKAR PRAMESTI NEGARA, S.H.",
	4: "Ir. SUDIRDJO",
	5: "AIRLANGGA JUSTITIA, S.H., M.H.",
	6: "FARADILA MAHRI, S.Pd.",
	7: "AINUNNISA AZIZAH, A.Md.",
	8: "KUNCORO HADIYANTO, S.E.",
	9: "RENOLD SIMANDJUNTAK, S.H.",
	10: "FITRIA PUJIATI",
};

const PSI = {
	nomer: 15,
	nama: "PSI",
	dapil: "DAPIL 1",
	1: "ALFIAN LIMARDI",
	2: "dr. MICHAEL LEKSODIMULYO",
	3: "YUSFIKA NANI SA'ADAH",
	4: "MUHAMMAD ROSULI, S.H., M.H.",
	5: "FANNY YUWONO",
	6: "WAHYU SANTOSO",
	7: "DANIEL LUKAS RORONG",
	8: "RACHMAT MUSA BUDIJANTO",
	9: "LILIK SYAFITRI",
	10: "MARTIN NARANTIKA SANTOSO",
};

const PERINDO = {
	nomer: 16,
	nama: "PERINDO",
	dapil: "DAPIL 1",
	1: "TOENING GOESTIATI",
	2: "ANUGRAH ARIYADI, S.H.",
	3: "ENDANG SOEWITO, S.Sos.",
	4: "TATIK EFFENDI, S.H.",
	5: "TOTON MARIYONO",
	6: "VENTJE N KALALO",
	7: "AGUS HARIYANTO",
	8: "EDY WINARTO",
	9: "NENENG SALMIYAH",
	10: "LISA",
};

const PPP = {
	nomer: 17,
	nama: "PPP",
	dapil: "DAPIL 1",
	1: "M. SAIFUL",
	2: "MOCH FARKAN",
	3: "VIOLA NANNY ARRUBIAH, A.Md.Keb.",
	4: "Ir. H. FARIED SYAIFULLAH",
	5: "MOHAMMAD PINDA",
	6: "ST.  FARIHA",
	7: "ALAM ALANG LAKSANA",
	8: "IRWANTO, S.H.",
	9: "AGUSTINAWATI",
	10: "MUHAMAD ARFAN, S.H.",
};

const PARTAI_UMMAT = {
	nomer: 24,
	nama: "PARTAI_UMMAT",
	dapil: "DAPIL 1",
	1: "IMIRIYA KUMALA, S.I.P.",
	2: "Ir. LOESI ROHMAJONI",
	3: "SUYITNO, M.Ag.",
	4: "Drs. WARDIONO SETIAWAN",
};

export { PKB, GERINDRA, PDIP, GOLKAR, NASDEM, PARTAI_BURUH, GELORA, PKS, PKN, HANURA, PARTAI_GARUDA, PAN, PBB, DEMOKRAT, PSI, PERINDO, PPP, PARTAI_UMMAT };
