// CALEG PUSAT
const PKB = {
	nomer: 1,
	nama: "PKB",
	1: "SYAIKHUL ISLAM",
	2: "DITA INDAH SARI, S.H., M.H.",
	3: "Dr. ARZETI BILBINA SETYAWAN, S.E.",
	4: "ABDUL ROCHIM, S.Sos.",
	5: "MUKAFI MAKKI, S.Hum.",
	6: "M. ZAENAB MALTUFAH, S.E., M.S.E.",
	7: "ACHMAD WAHYUDDIN, S.H., M.H.",
	8: "MUHAMMAD GHOZI ALFATIH",
	9: "SRI UNTARI PUJI HASTUTI, S.E., M.M.",
	10: "TEDDY SUGIHARTO, S.E.",
};

const GERINDRA = {
	nomer: 2,
	nama: "GERINDRA",
	1: "Ir. BAMBANG HARYO SOEKARTONO",
	2: "DHANI AHMAD PRASETYO",
	3: "KENASTI ARNINTA PUTRI",
	4: "RAHMAT MUHAJIRIN",
	5: "SUGENG RIBOWO",
	6: "Dra. DWI SEPTAHANY ISNANIEK",
	7: "NINIK ISTIANI, S.Adm.",
	8: "SALEH ALHASNI",
	9: "SRI PRIHATININGSIH, S.H., M.Kn.",
	10: "REFI AVIO ROSA",
};

const PDIP = {
	nomer: 3,
	nama: "PDIP",
	1: "PUTI GUNTUR SOEKARNO, S.I.P.",
	2: "BAMBANG DH",
	3: "Laksdya. TNI Dr. AGUS SETIADJI",
	4: "B. ZAELANI, S.E.",
	5: "ANDRE HEHANUSSA",
	6: "INDAH KURNIA",
	7: "FAOZAN AMAR",
	8: "SONNY SEWANTON SARAGIH, S.I.P.",
	9: "NUNING ESTI PALUPI",
	10: "ARIELLA HANA SINJAYA",
};

const GOLKAR = {
	nomer: 4,
	nama: "GOLKAR",
	1: "ADIES KADIR",
	2: "Dr. RORO DYAH EKO SETYOWATI",
	3: "Drs. Ec. ALI SAIBOO, M.M.",
	4: "Dr. ANDI BUDI SULISTIJANTO, S.H.",
	5: "Dra. FARAH TAMALIA",
	6: "Dr. ILYAS INDRA, S.H.I., M.H., M.M.",
	7: "M ISBAT ATIQILLAH PRANATA, S.H.",
	8: "BAMBANG BUDI SUWARSO, Ak.",
	9: "Dr. RADEN BESSE KARTONINGRAT, S.H.",
	10: "ADELA KANASYA ADIES",
};

const NASDEM = {
	nomer: 5,
	nama: "NASDEM",
	1: "MUHAMMAD SHOLEH, S.H.",
	2: "LITA MACHFUD ARIFIN",
	3: "Drs. H. HARUNA SOEMITRO, M.Si.",
	4: "KRISNA MUKTI",
	5: "Drs. IPONG MUCHLISSONI",
	6: "YANTI IRIANI PANE, S.T.",
	7: "M. RIZKY HIDAYATULLAH, S.E.",
	8: "MUHAMMAD DAFA",
	9: "AYU WULAN SARI",
	10: "MUSYAFAAH MIA KURNIATI",
};

const PARTAI_BURUH = {
	nomer: 6,
	nama: "PARTAI_BURUH",
	1: "AGUS SUPRIYANTO",
	2: "MOESTOPO, S.E., S.H., M.H.",
	3: "SRI ASTUTI",
	4: "MASKURI",
	5: "YULI DANIATI",
	6: "SUNGKONO ARI SAPUTRO",
	7: "GUNAWAN BASRI",
	8: "LUCKY CHRISTANO MASENGI SANGER",
	9: "YOLANDA AMALIA",
	10: "MOH AGUS BUDI HARIONO",
};

const GELORA = {
	nomer: 7,
	nama: "GELORA",
	1: "DODDY EKA PUTRA, S.T., M.M.",
	2: "KH. ACHMAD FATHONY",
	3: "DEWI AJUNI",
	4: "UMBANG PURYANTO",
	5: "RIZKY EKO NUGROHO",
	6: "CHURIYATUN NAFISAH",
	7: "WAHYU PRIHATIN",
};

const PKS = {
	nomer: 8,
	nama: "PKS",
	1: "Ir. H. SIGIT SOSIANTOMO",
	2: "RENI ASTUTI, S.Si., M.PSDM.",
	3: "dr. AGOES KOOSHARTORO, Sp.P.D.(K).",
	4: "H. JALALUDDIN ALHAM, S.I.P., M.Hum.",
	5: "WAHYU SRIONO",
	6: "dr. AUFIYA NAILY",
	7: "DIHIN SUPRIYANDINI, S.Farm.",
	8: "RUSFIAN EFFENDI, S.M., S.Ag., M.M.",
	9: "Drs. MUHAMMAD AZIZ",
	10: "HUSIN, S.E.",
};

const PKN = {
	nomer: 9,
	nama: "PKN",
	1: "IWAN WEDA, S.E., M.M., M.Mar.",
	2: "THERESIA LIZA DEWI W, S.H.",
	3: "IRNA LAKSMI LARASATI",
	4: "PRASETYONO",
	5: "RATNA PUSPITASARI",
	6: "ABDUL CHOLIQ ROSJIDI",
	7: "WAHYU HIDAYAT",
	8: "LILIK SUMIATI",
	9: "HESTY SULISTYOWATI, S.E.",
	10: "ANJAS MAULANA",
};

const HANURA = {
	nomer: 10,
	nama: "HANURA",
	1: "Dr. Ir. SUMARZEN MARZUKI, M.M.",
	2: "H. LUTFI HERMAWANSYAH",
	3: "ISDANIAR NOVI HIJRIANI",
	4: "FAJAR SUCAHYO",
	5: "EVA CYNTHIA DEVI, S.E.",
};

const PARTAI_GARUDA = {
	nomer: 11,
	nama: "PARTAI_GARUDA",
	1: "GANANG NIRWAN DARMAWAN",
	2: "OLIVIA MARGARETH PANJAITAN",
	3: "MOCH SALMAN AL FARIZI",
	4: "ATRINA ISTI OILINDA",
	5: "KHAIRUL AGUNG",
	6: "MAHNUN",
	7: "KAISAR HAIDAR ALI JAMAL",
	8: "DEVY PURNANING TIYAS",
	9: "ADINA NOVIANTI",
	10: "MUCH GUSTI WARDANA RAMADHAN",
};

const PAN = {
	nomer: 12,
	nama: "PAN",
	1: "SUNGKONO",
	2: "ARIZAL TOM LIWAFA, S.T., M.M.",
	3: "KURNIANTI HERDIANDARI, S.H.",
	4: "H. MOH. ZAINUL LUTFI",
	5: "H. MOH. TAUFIQULBAR, M.Si.",
	6: "ELI HESTINAH",
	7: "DIKKY SYADQOMULLAH, S.H.I., M.HES.",
	8: "YOOKY TJAHRIAL",
	9: "ENDAH PUSPITA ANDRIJANI",
	10: "Dr. Drs. H. ZAINAL ARIFIN, M.Pd.",
};

const PBB = {
	nomer: 13,
	nama: "PBB",
	1: "Ir. H. MOHAMMAD MASDUKI, S.H., M.H.",
	2: "ULFA AFIFAH ASHARINI",
	3: "AFFAN GHIFARI",
};

const DEMOKRAT = {
	nomer: 14,
	nama: "DEMOKRAT",
	1: "Dra. LUCY KURNIASARI",
	2: "H. M. AA LA NYALLA MAHMUD MATTALITTI",
	3: "JIMMY HIMAWAN, S.H.",
	4: "DONNY SOEHANDHONO",
	5: "INDAH NOVIANTI, S.T.",
	6: "SRI RAMADHANY",
	7: "MUHAMMAD RIDHA",
	8: "IR. MUHAMMAD IQBAL",
	9: "ZULFA NURDIANA PUTRI, A.Md.",
	10: "ROSANDI DHARMA",
};

const PSI = {
	nomer: 15,
	nama: "PSI",
	1: "PAULUS TOTOK LUSIDA",
	2: "BENNY BUDHIJANTO",
	3: "LIANA KURNIAWAN",
	4: "WAHYUDIN SOFYAN, S.E.",
	5: "ANDRE CAHYO NUGROHO",
	6: "INDAH IRIANI",
	7: "ANTONIUS RICKY HARTONO",
	8: "BAMBANG HONDIONO, S.E.",
	9: "IDA ANDRIANI",
	10: "ISWANTI",
};

const PERINDO = {
	nomer: 16,
	nama: "PERINDO",
	1: "ANGELA H. TANOESOEDIBJO, B.A.",
	2: "KomjenPol Dr. ANANG ISKANDAR",
	3: "ARNOLD POERNOMO",
	4: "NATALIA CECILIA TANUDJAJA, S.T.",
	5: "MUCHAMMAD AULIA SUNARYOHADI, S.H.",
	6: "A. WISHNU HANDOYONO",
	7: "HENRY MALCORPS",
	8: "DODY YUDHA M.R.",
	9: "RATNA DHAMAYANTI",
	10: "MOCHAMMAD ABDUL WAHID, S.H.",
};

const PPP = {
	nomer: 17,
	nama: "PPP",
	1: "GAMAL HARYO PUTRO",
	2: "H. M. TANZIL FURQON",
	3: "ERLYTA DWI AGUSTINA SIREGAR",
	4: "ACHMAD FIKRI HIDAYAT, S.H.",
	5: "H. ABDUL HANAN MAJDY, S.Kom.",
	6: "MAHARANI SITI SHOPIA, M.H.",
	7: "M. SAMSUL ARIFIN",
	8: "FAISAL AHMAD",
	9: "MAHMUDA",
	10: "JOKO DWITANTO",
};

const PARTAI_UMMAT = {
	nomer: 24,
	nama: "PARTAI_UMMAT",
	1: "Ir. SARDJONO BUDI SANTOSO",
	2: "MUNAWIR ANSHORY",
	3: "YULIDA TRI RATNA DEWI",
	4: "RISTANTO",
	5: "TRI KARDIASTUTI",
	6: "SUPARTIYANI",
	7: "ISFIANTORO",
	8: "ENDAH TRI UTAMI",
	9: "SANUSI PRASETYO",
	10: "SETYO NUGROHO",
};

export { PKB, GERINDRA, PDIP, GOLKAR, NASDEM, PARTAI_BURUH, GELORA, PKS, PKN, HANURA, PARTAI_GARUDA, PAN, PBB, DEMOKRAT, PSI, PERINDO, PPP, PARTAI_UMMAT };
