export const kelurahan = {
	Asemrowo: ["Asemrowo", "Genting Kalianak", "Tambak Sarioso"],
	Benowo: ["Kandangan", "Romokalisari", "Sememi", "Tambak Osowilangun"],
	Bubutan: ["Alun-Alun Contong", "Bubutan", "Gundih", "Jepara", "Tembok Dukuh"],
	Bulak: ["Bulak", "Kedungcowek", "Kenjeran", "Sukolilo Baru"],
	DukuhPakis: ["Dukuh Kupang", "Dukuh Pakis", "Gunung Sari", "Pradah Kalikendal"],
	Gayungan: ["Dukuh Menanggal", "Gayungan", "Ketintang", "Menanggal"],
	Genteng: ["Embong Kaliasin", "Genteng", "Kapasari", "Ketabang", "Peneleh"],
	Gubeng: ["Airlangga", "Barata Jaya", "Gubeng", "Kertajaya", "Mojo", "Pucangsewu"],
	GunungAnyar: ["Gunung Anyar", "Gunung Anyar Tambak", "Rungkut Menanggal", "Rungkut Tengah"],
	Jambangan: ["Jambangan", "Karah", "Kebonsari", "Pagesangan"],
	KarangPilang: ["Karang Pilang", "Kebraon", "Kedurus", "Warugunung"],
	Kenjeran: ["Bulakbanteng", "Tambakwedi", "Tanah Kali Kedinding", "Sidotopo Wetan"],
	Krembangan: ["Dupak", "Kemayoran", "Krembangan Selatan", "Morokrembangan", "Perak Barat"],
	Lakarsantri: ["Bangkingan", "Jeruk", "Lakarsantri", "Lidah Kulon", "Lidah Wetan", "Sumur Welut"],
	Mulyorejo: ["Dukuh Sutorejo", "Kalijudan", "Kalisari", "Kejawan Putih Tambak", "Manyar Sabrangan", "Mulyorejo"],
	PabeanCantian: ["Bongkaran", "Krembangan Utara", "Nyamplungan", "Tanjung Perak"],
	Pakal: ["Babat Jerawat", "Benowo", "Pakal", "Sumberejo"],
	Rungkut: ["Kali Rungkut", "Kedung Baruk", "Medokan Ayu", "Penjaringan Sari", "Rungkut Kidul", "Wonorejo"],
	Sambikerep: ["Bringin", "Made", "Lontar", "Sambikerep"],
	Sawahan: ["Banyu Urip", "Kupang Krajan", "Pakis", "Patemon", "Putat Jaya", "Sawahan"],
	Semampir: ["Ampel", "Pegirian", "Sidotopo", "Ujung", "Wonokusumo"],
	Simokerto: ["Kapasan", "Sidodadi", "Simokerto", "Simolawang", "Tambakrejo"],
	Sukolilo: ["Gebang Putih", "Keputih", "Klampisngasem", "Medokan Semampir", "Menur Pumpungan", "Nginden Jangkungan", "Semolowaru"],
	Sukomanunggal: ["Putatgede", "Simomulyo", "Simomulyo Baru", "Sonokwijenan", "Sukomanunggal", "Tanjungsari"],
	Tambaksari: ["Dukuh Setro", "Gading", "Kapas Madya", "Pacar Kembang", "Pacar Keling", "Ploso", "Rangkah", "Tambaksari"],
	Tandes: ["Balongsari", "Banjar Sugihan", "Karang Poh", "Manukan Kulon", "Manukan Wetan", "Tandes"],
	Tegalsari: ["Dr.Sutomo", "Kedungdoro", "Keputran", "Tegalsari", "Wonorejo"],
	TenggilisMejoyo: ["Kendangsari", "Kutisari", "Panjang Jiwo", "Tenggilis Mejoyo"],
	Wiyung: ["Babatan", "Balasklumprik", "Jajar Tunggal", "Wiyung"],
	Wonocolo: ["Bendul Merisi", "Jemur Wonosari", "Margorejo", "Sidosermo", "Siwalan Kerto"],
	Wonokromo: ["Darmo", "Jagir", "Ngagel", "Ngagelrejo", "Sawunggaling", "Wonokromo"],
};

export const kecamatan = [
	"Asemrowo",
	"Benowo",
	"Bubutan",
	"Bulak",
	"DukuhPakis",
	"Gayungan",
	"Genteng",
	"Gubeng",
	"GunungAnyar",
	"Jambangan",
	"KarangPilang",
	"Kenjeran",
	"Krembangan",
	"Lakarsantri",
	"Mulyorejo",
	"PabeanCantian",
	"Pakal",
	"Rungkut",
	"Sambikerep",
	"Sawahan",
	"Semampir",
	"Simokerto",
	"Sukolilo",
	"Sukomanunggal",
	"Tambaksari",
	"Tandes",
	"Tegalsari",
	"TenggilisMejoyo",
	"Wiyung",
	"Wonocolo",
	"Wonokromo",
];
