export const tps = {
	Asemrowo: [{ Asemrowo: 82 }, { "Genting Kalianak": 21 }, { "Tambak Sarioso": 20 }],
	Benowo: [{ Kandangan: 63 }, { Romokalisari: 8 }, { Sememi: 104 }, { "Tambak Osowilangun": 11 }],
	Bubutan: [{ "Alun-Alun Contong": 19 }, { Bubutan: 37 }, { Gundih: 73 }, { Jepara: 69 }, { "Tembok Dukuh": 70 }],
	Bulak: [{ Bulak: 57 }, { Kedungcowek: 17 }, { Kenjeran: 19 }, { "Sukolilo Baru": 26 }],
	DukuhPakis: [{ "Dukuh Kupang": 40 }, { "Dukuh Pakis": 40 }, { "Gunung Sari": 37 }, { "Pradah Kalikendal": 43 }],
	Gayungan: [{ "Dukuh Menanggal": 23 }, { Gayungan: 30 }, { Ketintang: 37 }, { Menanggal: 24 }],
	Genteng: [{ "Embong Kaliasin": 33 }, { Genteng: 24 }, { Kapasari: 46 }, { Ketabang: 21 }, { Peneleh: 45 }],
	Gubeng: [{ Airlangga: 55 }, { "Barata Jaya": 44 }, { Gubeng: 40 }, { Kertajaya: 69 }, { Mojo: 129 }, { Pucangsewu: 38 }],
	GunungAnyar: [{ "Gunung Anyar": 60 }, { "Gunung Anyar Tambak": 29 }, { "Rungkut Menanggal": 36 }, { "Rungkut Tengah": 38 }],
	Jambangan: [{ Jambangan: 31 }, { Karah: 43 }, { Kebonsari: 31 }, { Pagesangan: 37 }],
	KarangPilang: [{ "Karang Pilang": 23 }, { Kebraon: 80 }, { Kedurus: 74 }, { Warugunung: 26 }],
	Kenjeran: [{ Bulakbanteng: 89 }, { Tambakwedi: 51 }, { "Tanah Kali Kedinding": 157 }, { "Sidotopo Wetan": 161 }],
	Krembangan: [{ Dupak: 61 }, { Kemayoran: 48 }, { "Krembangan Selatan": 39 }, { Morokrembangan: 123 }, { "Perak Barat": 38 }],
	Lakarsantri: [{ Bangkingan: 24 }, { Jeruk: 24 }, { Lakarsantri: 22 }, { "Lidah Kulon": 46 }, { "Lidah Wetan": 32 }, { "Sumur Welut": 15 }],
	Mulyorejo: [{ "Dukuh Sutorejo": 45 }, { Kalijudan: 39 }, { Kalisari: 43 }, { "Kejawan Putih Tambak": 20 }, { "Manyar Sabrangan": 47 }, { Mulyorejo: 48 }],
	PabeanCantian: [{ Bongkaran: 29 }, { "Krembangan Utara": 46 }, { Nyamplungan: 24 }, { "Tanjung Perak": 115 }],
	Pakal: [{ "Babat Jerawat": 71 }, { Benowo: 32 }, { Pakal: 28 }, { Sumberejo: 33 }],
	Rungkut: [{ "Kali Rungkut": 63 }, { "Kedung Baruk": 45 }, { "Medokan Ayu": 77 }, { "Penjaringan Sari": 53 }, { "Rungkut Kidul": 37 }, { Wonorejo: 50 }],
	Sambikerep: [{ Bringin: 15 }, { Made: 25 }, { Lontar: 82 }, { Sambikerep: 57 }],
	Sawahan: [{ "Banyu Urip": 107 }, { "Kupang Krajan": 65 }, { Pakis: 97 }, { Patemon: 103 }, { "Putat Jaya": 126 }, { Sawahan: 52 }],
	Semampir: [{ Ampel: 51 }, { Pegirian: 84 }, { Sidotopo: 86 }, { Ujung: 92 }, { Wonokusumo: 186 }],
	Simokerto: [{ Kapasan: 43 }, { Sidodadi: 46 }, { Simokerto: 60 }, { Simolawang: 59 }, { Tambakrejo: 55 }],
	Sukolilo: [{ "Gebang Putih": 20 }, { Keputih: 54 }, { Klampisngasem: 47 }, { "Medokan Semampir": 53 }, { "Menur Pumpungan": 44 }, { "Nginden Jangkungan": 41 }, { Semolowaru: 54 }],
	Sukomanunggal: [{ Putatgede: 20 }, { Simomulyo: 63 }, { "Simomulyo Baru": 115 }, { Sonokwijenan: 22 }, { Sukomanunggal: 32 }, { Tanjungsari: 34 }],
	Tambaksari: [{ "Dukuh Setro": 61 }, { Gading: 85 }, { "Kapas Madya": 106 }, { "Pacar Kembang": 110 }, { "Pacar Keling": 62 }, { Ploso: 97 }, { Rangkah: 47 }, { Tambaksari: 55 }],
	Tandes: [{ Balongsari: 25 }, { "Banjar Sugihan": 31 }, { "Karang Poh": 42 }, { "Manukan Kulon": 99 }, { "Manukan Wetan": 25 }, { Tandes: 26 }],
	Tegalsari: [{ "Dr.Sutomo": 45 }, { Kedungdoro: 65 }, { Keputran: 43 }, { Tegalsari: 50 }, { Wonorejo: 73 }],
	TenggilisMejoyo: [{ Kendangsari: 42 }, { Kutisari: 52 }, { "Panjang Jiwo": 37 }, { "Tenggilis Mejoyo": 31 }],
	Wiyung: [{ Babatan: 81 }, { Balasklumprik: 38 }, { "Jajar Tunggal": 32 }, { Wiyung: 52 }],
	Wonocolo: [{ "Bendul Merisi": 46 }, { "Jemur Wonosari": 57 }, { Margorejo: 30 }, { Sidosermo: 36 }, { "Siwalan Kerto": 47 }],
	Wonokromo: [{ Darmo: 43 }, { Jagir: 59 }, { Ngagel: 34 }, { Ngagelrejo: 126 }, { Sawunggaling: 75 }, { Wonokromo: 109 }],
};

export const tpscontoh = { Asemrowo: [{ Darmo: 43 }, { Jagir: 59 }], Wonocolo: [{ "Bendul Merisi": 46 }, { "Jemur Wonosari": 57 }] };
